DYNAMO_URL = 'https://dynamodb.us-west-1.amazonaws.com'
DYNAMO_TABLE = 'kmeansservice'
DYNAMO_REGION = 'us-west-1'
S3_BUCKET = 'kmeansservice'
SNS_TOPIC_ARN = 'arn:aws:sns:us-west-1:000169391513:kmeans-service'
CELERY_BROKER = 'amqp://localhost//'